{{ config(
    database='STAGING_DB',
    schema='STG_SALES_SCHEMA',
    alias='products',
    materialized='view'
) }}


SELECT 
CAST(PRODUCT_ID AS NUMBER) AS PRODUCT_ID,
NAME,
CATEGORY,
SUBCATEGORY,
BRAND,
CAST(PRICE_CENTS AS NUMBER) AS PRICE_CENTS,
CAST(COST_CENTS AS NUMBER) AS COST_CENTS,
SKU,
STATUS,
TRY_CAST(CREATED_AT AS TIMESTAMP) AS CREATED_AT,
TRY_CAST(UPDATED_AT AS TIMESTAMP) AS UPDATED_AT

FROM RAW_DATA_DB.TRANSACTIONAL_SCHEMA.PRODUCTS

