{{ config(
    database='STAGING_DB',
    schema='STG_SALES_SCHEMA',
    alias='order_line_items',
    materialized='view'
) }}


SELECT 
CAST(ORDER_LINE_ITEM_ID AS NUMBER) AS ORDER_LINE_ITEM_ID,
CAST(ORDER_ID AS NUMBER) AS ORDER_ID,
CAST(PRODUCT_ID AS NUMBER) AS PRODUCT_ID,
CAST(QUANTITY AS NUMBER) AS QUANTITY,
CAST(UNIT_PRICE_CENTS AS NUMBER) AS UNIT_PRICE_CENTS,
CAST(TOTAL_PRICE_CENTS AS NUMBER) AS TOTAL_PRICE_CENTS,
CAST(DISCOUNT_AMOUNT_CENTS AS NUMBER) AS DISCOUNT_AMOUNT_CENTS

FROM RAW_DATA_DB.TRANSACTIONAL_SCHEMA.ORDER_LINE_ITEMS