{{ config(
    database='STAGING_DB',
    schema='STG_SALES_SCHEMA',
    alias='orders',
    materialized='view'
) }}

SELECT 
CAST(ORDER_ID AS NUMBER) as ORDER_ID,
CAST(CUSTOMER_ID AS NUMBER) AS CUSTOMER_ID,
TRY_CAST(ORDER_DATE AS DATE) AS ORDER_DATE,
CAST(TOTAL_AMOUNT_CENTS AS NUMBER) AS TOTAL_AMOUNT_CENTS,
CAST(TAX_AMOUNT_CENTS AS NUMBER) AS TAX_AMOUNT_CENTS,
CAST(SHIPPING_AMOUNT_CENTS AS NUMBER) AS SHIPPING_AMOUNT_CENTS,
CAST(DISCOUNT_AMOUNT_CENTS AS NUMBER) AS DISCOUNT_AMOUNT_CENTS,
STATUS,
PAYMENT_METHOD,
SHIPPING_ADDRESS,
TRY_CAST(CREATED_AT AS TIMESTAMP) AS CREATED_AT,
TRY_CAST(UPDATED_AT AS TIMESTAMP) AS UPDATED_AT
FROM RAW_DATA_DB.TRANSACTIONAL_SCHEMA.ORDERS